cloud:
  aws:
    credentials:
      access-key: KEY
      secret-key: SECRET
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: bukcketname

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB